/* SPDX-License-Identifier: GPL-2.0 */
#ifndef __IMGSENSOR_PLATFORM_H__
#define __IMGSENSOR_PLATFORM_H__

#if (defined(TCT_CAMERA_PROJECT_BUFFALOTMO)|| defined(CONFIG_MTK_ODIN5GTMO_K419_CAMERA))
//#define MIPI_SWITCH
#else
#define MIPI_SWITCH
#endif

enum IMGSENSOR_HW_ID {
	IMGSENSOR_HW_ID_MCLK,
	IMGSENSOR_HW_ID_REGULATOR,
	IMGSENSOR_HW_ID_GPIO,
	IMGSENSOR_HW_ID_MAX_NUM,
	IMGSENSOR_HW_ID_NONE = -1
};
#endif
