obj-$(CONFIG_POWER_AVS)		+= avs/
obj-$(CONFIG_POWER_RESET)	+= reset/
obj-$(CONFIG_POWER_SUPPLY)	+= supply/
# Begin added by bin.song.hz for task 9772991 on 2020-08-26
obj-$(CONFIG_TCPC_WUSB3801X)		+= tcpc_wusb3801x.o
# End added by bin.song.hz for task 9772991 on 2020-08-26
