#
# Makefile for all kinds of Fingerprint
#
obj-$(CONFIG_JRD_SUNWAVE_FINGERPRINT) += sunwave/
# Begin Modified by yuduan.xie for Task 8177729 on 2019.08.05
obj-$(CONFIG_FOCAL_FINGERPRINT) += focaltech/
# End Modified by yuduan.xie for Task 8177729 on 2019.08.05

