# [TCTNB][FINGERPRINT]Added_begin by Jiancong.Huang for F11394572 at 2021/8/12
obj-$(CONFIG_FINGERPRINT_Focaltech_Capvitive_B) += focaltech_capcitive_b/
# [TCTNB][FINGERPRINT]Added_end by Jiancong.Huang for F11394572 at 2021/8/12

#added by qianbo.pan for Task:11387489 on 2021.08.24
obj-$(CONFIG_MTK_FINGERPRINT_SUNWAVECORP)   += sunwave_fp/

#start, guang.xiao, 2022/02/27, fingerprint porting
obj-$(CONFIG_FOCALTECH_FINGERPRINT)   += buffalotmo/focaltech/
obj-$(CONFIG_SUNWAVEFP_FINGERPRINT)   += buffalotmo/sunwave_fp/
#end, guang.xiao, 2022/02/27, fingerprint porting
# Begin added by liuyu for passat-T fingerprint porting on 2022-5-10
obj-$(CONFIG_FINGERPRINT_CHIPONE_TCT) += TCT-fingerprint/chipone_fp/
obj-$(CONFIG_FINGERPRINT_FOCALTECH_TCT) += TCT-fingerprint/focaltech/
# End added by liuyu for passat-T fingerprint porting on 2022-5-10

#Begin added by liangjiaqiang for MODEL3-1890 on 2022-09-15
obj-$(CONFIG_FINGERPRINT_REGULATOR_MT6371) += TCT-fingerprint/regulator/
#End added by liangjiaqiang for MODEL3-1890 on 2022-09-15

# Begin added by weizhen.pang for EncoreVZW FR ENCOREVZW-6415 on 20221011
obj-$(CONFIG_FINGERPRINT_FORTSENSE_FP) += fortsense_fp/
# End added by weizhen.pang for EncoreVZW FR ENCOREVZW-6415 on 20221011
