obj-$(CONFIG_TCT_DEVICEINFO) += device-info.o devinfo_emmc.o deviceinfo_lcm.o
obj-$(CONFIG_TCT_DEVICEINFO_UFS) += devinfo_ufs.o
obj-y += tct_display_touch_interface.o tct_misc_common_interface.o
obj-$(CONFIG_TCT_DMCC) += dmcc.o
obj-$(CONFIG_INTELLIGENT_RECLAIM) += intelligent_reclaim.o user_action_detect.o
obj-$(CONFIG_TCT_MMPRESSURE_DETECT) += mmpressure_detect.o
obj-$(CONFIG_TCT_LIMIT_MEDIASCANNER) += limit_mediascanner.o
