#
# This program is free software and is provided to you under the terms of the
# GNU General Public License version 2 as published by the Free Software
# Foundation, and any use by you of this program is subject to the terms
# of such GNU licence.
#
# A copy of the licence is included with the program, and can also be obtained
# from Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
# Boston, MA  02110-1301, USA.
#
#

#MALI_GMC_COMPRESS_SIZE ?= 250

ifeq ($(CONFIG_GRAPHICS_GT),y)
# Set up our defines, which will be passed to gcc
#DEFINES += \
#	-DMALI_GMC_COMPRESS_SIZE=$(MALI_GMC_COMPRESS_SIZE)

ccflags-y += \
	-I$(src)/platform/$(MALI_PLATFORM_DIR)/gt

subdir-ccflags-y += \
	-I$(src)/platform/$(MALI_PLATFORM_DIR)/gt

SRC += platform/$(MALI_PLATFORM_DIR)/gt/mali_kbase_gt.c

mali_kbase-y += \
	platform/$(MALI_PLATFORM_DIR)/gt/mali_kbase_gt.o
endif