#
# Copyright (C) 2015 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#

# legacy chip devinfo driver
obj-y += devinfo.o
#BEGIN add by wang.zhou for ENCORECKT-2746
obj-$(CONFIG_KERNEL_ENV_TCT) += kernel_env_ro.o
#END add by wang.zhou for ENCORECKT-2746
