obj-$(CONFIG_TOUCHSCREEN_MTK_FT5446_BANGKOKTF) += focaltech_upgrade_ft5422.o
obj-$(CONFIG_TOUCHSCREEN_MTK_FT5446_BANGKOKTF) += focaltech_upgrade_ft5422u.o
obj-$(CONFIG_TOUCHSCREEN_MTK_FT5446_BANGKOKTF) += focaltech_upgrade_ft5446_p03.o
